### @name getTickets
GET http://localhost:3000/api/tickets/1

### @name createTicket
POST http://localhost:3000/api/tickets
Content-Type: application/json

{
  "ticketId": "1",
  "title": "Test Ticket"
}

### @name updateTicket
PUT http://localhost:3000/api/tickets/1
Content-Type: application/json

{
  "title": "Updated Ticket"
}

### @name deleteTicket
DELETE http://localhost:3000/api/tickets/1
